storage: .verdaccio
auth:
  htpasswd:
    file: .verdaccio/htpasswd
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
  amzn:
    url: https://k-artifactory-external.labcollab.net/artifactory/api/npm/kepler-npm-prod-local/
    auth:
      type: bearer
      token_env: AMZN_AUTHENTICATION
log:
  level: trace
max_body_size: 100mb
packages:
  '@bugsnag/safe-json-stringify':
    access: $anonymous
    proxy: npmjs
  '@bugsnag/cuid':
    access: $anonymous
    proxy: npmjs
  '@bugsnag/vega':
    access: $anonymous
    publish: $anonymous
  '@bugsnag/vega-*':
    access: $anonymous
    publish: $anonymous
  '@bugsnag/*':
    access: $anonymous
    proxy: npmjs
  '@amzn/*':
    access: $anonymous
    proxy: amzn
  '@*/*':
    access: $anonymous
    proxy: npmjs
  '**':
    access: $anonymous
    proxy: npmjs
