/**
 * This code was generated by the Kepler Codegen tool.
 * 
 * It is provided as a starting template and can be modified.
 * 
 * @generated by GenerateModuleH.js
 */

#include "generated/BugsnagFileIOSpec.h"

namespace bugsnag {

class BugsnagFileIO : public BugsnagFileIOSpec {
public:
  BugsnagFileIO();
  ~BugsnagFileIO() noexcept;

  com::amazon::kepler::turbomodule::JSObject readTextFile(std::string path) override;
  com::amazon::kepler::turbomodule::ArrayBuffer readFile(std::string path) override;
  com::amazon::kepler::turbomodule::JSObject writeTextFile(std::string path, std::string content) override;
  com::amazon::kepler::turbomodule::JSArray listDirectory(std::string dir) override;
  bool mkdir(std::string dir) override;
  bool deleteFile(std::string path) override;
  std::string sha1(com::amazon::kepler::turbomodule::ArrayBuffer data) override;
};

} // namespace bugsnag
