/**
 * This code was generated by the Kepler Codegen tool.
 * 
 * It is provided as a starting template and can be modified.
 * 
 * @generated by GenerateModuleH.js
 */

#include "generated/BugsnagVegaNativeSpec.h"

namespace BugsnagVegaNativeTurboModule {

class BugsnagVegaNative : public BugsnagVegaNativeSpec {
public:
  BugsnagVegaNative();
  ~BugsnagVegaNative() noexcept;

  com::amazon::kepler::turbomodule::JSObject configure(com::amazon::kepler::turbomodule::JSObject configuration) override;
  void markLaunchCompleted() override;
  std::string getDeviceID() override;
  void setDeviceID(std::string id) override;
  std::string generateUUID() override;
  void leaveBreadcrumb(com::amazon::kepler::turbomodule::JSObject crumb) override;
  void setMetadata(std::string metadataStr) override;
  void clearMetadata() override;
  void setFeatures(std::string featuresStr) override;
  void clearFeatures() override;
  void setUser(com::amazon::kepler::turbomodule::JSObject userInfo) override;
  void clearUser() override;
  void setApp(com::amazon::kepler::turbomodule::JSObject appInfo) override;
  void setDevice(com::amazon::kepler::turbomodule::JSObject deviceInfo) override;
  void nativeCrash() override;
};

} // namespace BugsnagVegaNativeTurboModule
