/**
 * This code was generated by the Kepler Codegen tool.
 * 
 * It is provided as a starting template and can be modified.
 * 
 * @generated by GenerateModuleCpp.js
 */

#include "BugsnagVegaNative.h"

using namespace com::amazon::kepler::turbomodule;

namespace BugsnagVegaNativeTurboModule {

BugsnagVegaNative::BugsnagVegaNative() {}
BugsnagVegaNative::~BugsnagVegaNative() noexcept {};

com::amazon::kepler::turbomodule::JSObject BugsnagVegaNative::configure(com::amazon::kepler::turbomodule::JSObject configuration) {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

void BugsnagVegaNative::markLaunchCompleted() {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

std::string BugsnagVegaNative::getDeviceID() {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

void BugsnagVegaNative::setDeviceID(std::string id) {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

std::string BugsnagVegaNative::generateUUID() {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

void BugsnagVegaNative::leaveBreadcrumb(com::amazon::kepler::turbomodule::JSObject crumb) {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

void BugsnagVegaNative::setMetadata(std::string metadataStr) {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

void BugsnagVegaNative::clearMetadata() {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

void BugsnagVegaNative::setFeatures(std::string featuresStr) {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

void BugsnagVegaNative::clearFeatures() {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

void BugsnagVegaNative::setUser(com::amazon::kepler::turbomodule::JSObject userInfo) {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

void BugsnagVegaNative::clearUser() {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

void BugsnagVegaNative::setApp(com::amazon::kepler::turbomodule::JSObject appInfo) {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

void BugsnagVegaNative::setDevice(com::amazon::kepler::turbomodule::JSObject deviceInfo) {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

void BugsnagVegaNative::nativeCrash() {
  // Your implementation here
  throw std::logic_error("Function not yet implemented");
}

} // namespace BugsnagVegaNativeTurboModule
