# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node CI

on: [push]

env:
  AMZN_AUTHENTICATION: ${{ secrets.AMZN_AUTHENTICATION }}

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install -g verdaccio@5.29.0
      - run: npm run local-npm:start &
      - run: rm -f package-lock.json && npm install --registry 'http://0.0.0.0:5539' --legacy-peer-deps
      - run: npm run test:lint

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm install -g verdaccio@5.29.0
      - run: npm run local-npm:start &
      - run: rm -f package-lock.json && npm install --registry 'http://0.0.0.0:5539' --legacy-peer-deps
      - run: npm run test:unit
